# If deployed to AWS EKS, set up ExternalDNS
cluster: docker-desktop   # aws | docker-desktop | kind | minikube

# Ingress settings
ingress:
  enable: false  # true | false, if not true ingress is not deployed
  port: 80
  hostname: www.livinginatinyroom.net  # AWS only, used by ExternalDNS

# ExternalDNS settings (AWS only)
externalDns:
  namespace: external-dns
