version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: prob:0.3
    container_name: prob
    hostname: prob
    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - prob_network

networks:
  prob_network:
