version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - app=Prob.dll
    image: prob:0.2
    ports:
      - 81:80
      - 82:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=82
      - ASPNETCORE_Kestrel__Certificates__Default__Password=p@assw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
      - prob_network
    volumes:
      - ~/.aspnet/https:/https:ro
networks:
  prob_network:
