version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - app=Prob.dll
    image: ${APP_TAG}
    ports:
      - 8090:8080
      - 8091:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTPS_PORT=8091
      - ASPNETCORE_Kestrel__Certificates__Default__Password=p@assw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
      - prob_network
networks:
  prob_network:
